[package]
name = "scroxy"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
http = "0.2.9"
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.3", features = ["full"] }
log = "0.4.17"
tokio = { version = "1.27.0", features = ["full"] }
